# See https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  # Enable version updates for pip
  - package_ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
